# Configuración específica del servicio de ventas
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lucaticket_ventas_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# LucaBanking config
lucabanking:
  url: http://localhost:8082
  endpoint:
    compra: /pasarela/compra
